metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.1.110, mac: '08:bf:b8:00:1a:a7', disk: nvme0n1, network_interface: enp9s0}
#    workers:
#      hosts:
#        metal0: { ansible_host: 192.168.1.110, mac: '08:BF:B8:00:1A:A7', disk: sda, network_interface: eno1 }
